name = input("what is your name?")
result1 = name.upper()
print(result1)
result2 = name.lower()
print(result2)
result3 = name.title()
print(result3)
result4 = name.capitalize()
print(result4)
result5 = name.swapcase()
print(result5)
result6 = name.isdigit()
print(result6)
result7 = name.isalpha()
print(result7)
phone_number = input("what is your phone number?")
result8 = phone_number.isdigit()
print(result8)
phone_number = phone_number.replace("-", " ")
print(phone_number)
result9 = phone_number.isdigit()
print(result9)
result10 = phone_number.split()
print(result10)